apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      meta.helm.sh/release-name: arc
      meta.helm.sh/release-namespace: arc-systems
    creationTimestamp: "2025-12-13T01:43:04Z"
    generation: 3
    labels:
      actions.github.com/controller-service-account-name: arc-gha-rs-controller
      actions.github.com/controller-service-account-namespace: arc-systems
      app.kubernetes.io/instance: arc
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: gha-rs-controller
      app.kubernetes.io/namespace: arc-systems
      app.kubernetes.io/part-of: gha-rs-controller
      app.kubernetes.io/version: 0.13.0
      helm.sh/chart: gha-rs-controller-0.13.0
    name: arc-gha-rs-controller
    namespace: arc-systems
    resourceVersion: "11953265"
    uid: e82c22f9-e981-46fb-b60f-065d3b117e25
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: arc
        app.kubernetes.io/name: gha-rs-controller
        app.kubernetes.io/namespace: arc-systems
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/default-container: manager
          kubectl.kubernetes.io/restartedAt: "2025-12-12T20:50:46-05:00"
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: controller-manager
          app.kubernetes.io/instance: arc
          app.kubernetes.io/name: gha-rs-controller
          app.kubernetes.io/namespace: arc-systems
          app.kubernetes.io/part-of: gha-rs-controller
          app.kubernetes.io/version: 0.13.0
      spec:
        containers:
        - args:
          - --auto-scaling-runner-set-only
          - --log-level=info
          - --log-format=text
          - --runner-max-concurrent-reconciles=2
          - --update-strategy=immediate
          - --listener-metrics-addr=0
          - --listener-metrics-endpoint=
          - --metrics-addr=0
          command:
          - /manager
          env:
          - name: CONTROLLER_MANAGER_CONTAINER_IMAGE
            value: ghcr.io/actions/gha-runner-scale-set-controller:0.13.0
          - name: CONTROLLER_MANAGER_POD_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          image: ghcr.io/actions/gha-runner-scale-set-controller:0.13.0
          imagePullPolicy: IfNotPresent
          name: manager
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /tmp
            name: tmp
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: arc-gha-rs-controller
        serviceAccountName: arc-gha-rs-controller
        terminationGracePeriodSeconds: 10
        volumes:
        - emptyDir: {}
          name: tmp
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2025-12-13T01:43:05Z"
      lastUpdateTime: "2025-12-18T05:34:29Z"
      message: ReplicaSet "arc-gha-rs-controller-6d9d6bc79b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2025-12-19T13:21:37Z"
      lastUpdateTime: "2025-12-19T13:21:37Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 3
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
      dmVyLWNhQDE3NjIzMTk3MDUwHhcNMjUxMTA1MDUxNTA1WhcNMzUxMTAzMDUxNTA1
      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3NjIzMTk3MDUwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAAR7AJxksdMJZVIqsOrjf54yL6K7iY/JWSs9ZkQg0AUk
      aO30K0wLuHk4cK2eTPp/VQfmoT2dKjclRpDQ0VSUKWi2o0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUf6j/2FFh3fnWFj0FbbrB
      8UWVKzIwCgYIKoZIzj0EAwIDSAAwRQIhAJMPsstsw64+5mY7QIjcRxICHdHjksj3
      FVMXbjV+OBPtAiBzvKXcXD6YxhyxvDyHZ/kYyX95MPXYfd/wutZ6iyAOrQ==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2025-12-13T01:43:04Z"
    name: kube-root-ca.crt
    namespace: arc-systems
    resourceVersion: "9934632"
    uid: a2d640be-17bc-44d3-ace5-65c4649b9145
kind: List
metadata:
  resourceVersion: ""
